// Generated by wayland-swift-scanner from wayland.xml. Do not edit.
// Regenerate with `make protocols`.

/// wl_display: core global object
public enum WlDisplay: Interface {
    public static let name = "wl_display"
    public static let version: UInt32 = 1

    public enum Request {
        /// asynchronous roundtrip
        case sync(callback: NewID<WlCallback>)
        /// get global registry object
        case getRegistry(registry: NewID<WlRegistry>)
    }

    public static func decode(opcode: UInt16, from message: inout MessageReader, version: UInt32) throws(ProtocolError) -> Request {
        switch opcode {
        case 0:
            let callback = try message.newID(WlCallback.self, version: version)
            return .sync(callback: callback)
        case 1:
            let registry = try message.newID(WlRegistry.self, version: version)
            return .getRegistry(registry: registry)
        default:
            throw message.invalidOpcode(opcode)
        }
    }

    public static func isDestructor(opcode: UInt16) -> Bool {
        false
    }

    /// global error values
    public enum ErrorCode: UInt32, Sendable {
        /// server couldn't find object
        case invalidObject = 0
        /// method doesn't exist on the specified interface or malformed request
        case invalidMethod = 1
        /// server is out of memory
        case noMemory = 2
        /// implementation error in compositor
        case implementation = 3
    }
}

extension Resource where I == WlDisplay {
    /// fatal error event
    public func sendError(objectId: AnyResource, code: UInt32, message: String) {
        guard var event = beginEvent(opcode: 0, since: 1) else { return }
        event.object(objectId)
        event.uint(code)
        event.string(message)
        send(event)
    }

    /// acknowledge object ID deletion
    public func sendDeleteId(id: UInt32) {
        guard var event = beginEvent(opcode: 1, since: 1) else { return }
        event.uint(id)
        send(event)
    }
}

/// wl_registry: global registry object
public enum WlRegistry: Interface {
    public static let name = "wl_registry"
    public static let version: UInt32 = 1

    public enum Request {
        /// bind an object to the display
        case bind(name: UInt32, id: UntypedNewID)
    }

    public static func decode(opcode: UInt16, from message: inout MessageReader, version: UInt32) throws(ProtocolError) -> Request {
        switch opcode {
        case 0:
            let name = try message.uint()
            let id = try message.untypedNewID()
            return .bind(name: name, id: id)
        default:
            throw message.invalidOpcode(opcode)
        }
    }

    public static func isDestructor(opcode: UInt16) -> Bool {
        false
    }
}

extension Resource where I == WlRegistry {
    /// announce global object
    public func sendGlobal(name: UInt32, interface: String, version: UInt32) {
        guard var event = beginEvent(opcode: 0, since: 1) else { return }
        event.uint(name)
        event.string(interface)
        event.uint(version)
        send(event)
    }

    /// announce removal of global object
    public func sendGlobalRemove(name: UInt32) {
        guard var event = beginEvent(opcode: 1, since: 1) else { return }
        event.uint(name)
        send(event)
    }
}

/// wl_callback: callback object
public enum WlCallback: Interface {
    public static let name = "wl_callback"
    public static let version: UInt32 = 1

    public enum Request {
    }

    public static func decode(opcode: UInt16, from message: inout MessageReader, version: UInt32) throws(ProtocolError) -> Request {
        switch opcode {
        default:
            throw message.invalidOpcode(opcode)
        }
    }

    public static func isDestructor(opcode: UInt16) -> Bool {
        false
    }
}

extension Resource where I == WlCallback {
    /// done event
    public func sendDone(callbackData: UInt32) {
        guard var event = beginEvent(opcode: 0, since: 1) else { return }
        event.uint(callbackData)
        send(event)
    }
}

/// wl_compositor: the compositor singleton
public enum WlCompositor: Interface {
    public static let name = "wl_compositor"
    public static let version: UInt32 = 7

    public enum Request {
        /// create new surface
        case createSurface(id: NewID<WlSurface>)
        /// create new region
        case createRegion(id: NewID<WlRegion>)
        /// destroy wl_compositor
        case release
    }

    public static func decode(opcode: UInt16, from message: inout MessageReader, version: UInt32) throws(ProtocolError) -> Request {
        switch opcode {
        case 0:
            let id = try message.newID(WlSurface.self, version: version)
            return .createSurface(id: id)
        case 1:
            let id = try message.newID(WlRegion.self, version: version)
            return .createRegion(id: id)
        case 2:
            guard version >= 7 else { throw message.invalidOpcode(opcode) }
            return .release
        default:
            throw message.invalidOpcode(opcode)
        }
    }

    public static func isDestructor(opcode: UInt16) -> Bool {
        [2].contains(opcode)
    }
}

/// wl_shm_pool: a shared memory pool
public enum WlShmPool: Interface {
    public static let name = "wl_shm_pool"
    public static let version: UInt32 = 3

    public enum Request {
        /// create a buffer from the pool
        case createBuffer(id: NewID<WlBuffer>, offset: Int32, width: Int32, height: Int32, stride: Int32, format: UInt32)
        /// destroy the pool
        case destroy
        /// change the size of the pool mapping
        case resize(size: Int32)
    }

    public static func decode(opcode: UInt16, from message: inout MessageReader, version: UInt32) throws(ProtocolError) -> Request {
        switch opcode {
        case 0:
            let id = try message.newID(WlBuffer.self, version: version)
            let offset = try message.int()
            let width = try message.int()
            let height = try message.int()
            let stride = try message.int()
            let format = try message.uint()
            return .createBuffer(id: id, offset: offset, width: width, height: height, stride: stride, format: format)
        case 1:
            return .destroy
        case 2:
            let size = try message.int()
            return .resize(size: size)
        default:
            throw message.invalidOpcode(opcode)
        }
    }

    public static func isDestructor(opcode: UInt16) -> Bool {
        [1].contains(opcode)
    }

    /// wl_shm_pool error values
    public enum ErrorCode: UInt32, Sendable {
        /// buffer format is not known
        case invalidFormat = 0
        /// invalid size or stride during buffer creation
        case invalidStride = 1
    }
}

/// wl_shm: shared memory support
public enum WlShm: Interface {
    public static let name = "wl_shm"
    public static let version: UInt32 = 3

    public enum Request {
        /// create a shm pool
        case createPool(id: NewID<WlShmPool>, fd: Int32, size: Int32)
        /// release the shm object
        case release
    }

    public static func decode(opcode: UInt16, from message: inout MessageReader, version: UInt32) throws(ProtocolError) -> Request {
        switch opcode {
        case 0:
            let id = try message.newID(WlShmPool.self, version: version)
            let fd = try message.fd()
            let size = try message.int()
            return .createPool(id: id, fd: fd, size: size)
        case 1:
            guard version >= 2 else { throw message.invalidOpcode(opcode) }
            return .release
        default:
            throw message.invalidOpcode(opcode)
        }
    }

    public static func isDestructor(opcode: UInt16) -> Bool {
        [1].contains(opcode)
    }

    /// wl_shm error values
    public enum ErrorCode: UInt32, Sendable {
        /// buffer format is not known
        case invalidFormat = 0
        /// invalid size or stride during pool creation
        case invalidStride = 1
        /// mmapping the file descriptor failed
        case invalidFd = 2
    }

    /// pixel formats
    public enum Format: UInt32, Sendable {
        /// 32-bit ARGB format, [31:0] A:R:G:B 8:8:8:8 little endian
        case argb8888 = 0
        /// 32-bit RGB format, [31:0] x:R:G:B 8:8:8:8 little endian
        case xrgb8888 = 1
        /// 8-bit color index format, [7:0] C
        case c8 = 0x20203843
        /// 8-bit RGB format, [7:0] R:G:B 3:3:2
        case rgb332 = 0x38424752
        /// 8-bit BGR format, [7:0] B:G:R 2:3:3
        case bgr233 = 0x38524742
        /// 16-bit xRGB format, [15:0] x:R:G:B 4:4:4:4 little endian
        case xrgb4444 = 0x32315258
        /// 16-bit xBGR format, [15:0] x:B:G:R 4:4:4:4 little endian
        case xbgr4444 = 0x32314258
        /// 16-bit RGBx format, [15:0] R:G:B:x 4:4:4:4 little endian
        case rgbx4444 = 0x32315852
        /// 16-bit BGRx format, [15:0] B:G:R:x 4:4:4:4 little endian
        case bgrx4444 = 0x32315842
        /// 16-bit ARGB format, [15:0] A:R:G:B 4:4:4:4 little endian
        case argb4444 = 0x32315241
        /// 16-bit ABGR format, [15:0] A:B:G:R 4:4:4:4 little endian
        case abgr4444 = 0x32314241
        /// 16-bit RGBA format, [15:0] R:G:B:A 4:4:4:4 little endian
        case rgba4444 = 0x32314152
        /// 16-bit BGRA format, [15:0] B:G:R:A 4:4:4:4 little endian
        case bgra4444 = 0x32314142
        /// 16-bit xRGB format, [15:0] x:R:G:B 1:5:5:5 little endian
        case xrgb1555 = 0x35315258
        /// 16-bit xBGR 1555 format, [15:0] x:B:G:R 1:5:5:5 little endian
        case xbgr1555 = 0x35314258
        /// 16-bit RGBx 5551 format, [15:0] R:G:B:x 5:5:5:1 little endian
        case rgbx5551 = 0x35315852
        /// 16-bit BGRx 5551 format, [15:0] B:G:R:x 5:5:5:1 little endian
        case bgrx5551 = 0x35315842
        /// 16-bit ARGB 1555 format, [15:0] A:R:G:B 1:5:5:5 little endian
        case argb1555 = 0x35315241
        /// 16-bit ABGR 1555 format, [15:0] A:B:G:R 1:5:5:5 little endian
        case abgr1555 = 0x35314241
        /// 16-bit RGBA 5551 format, [15:0] R:G:B:A 5:5:5:1 little endian
        case rgba5551 = 0x35314152
        /// 16-bit BGRA 5551 format, [15:0] B:G:R:A 5:5:5:1 little endian
        case bgra5551 = 0x35314142
        /// 16-bit RGB 565 format, [15:0] R:G:B 5:6:5 little endian
        case rgb565 = 0x36314752
        /// 16-bit BGR 565 format, [15:0] B:G:R 5:6:5 little endian
        case bgr565 = 0x36314742
        /// 24-bit RGB format, [23:0] R:G:B little endian
        case rgb888 = 0x34324752
        /// 24-bit BGR format, [23:0] B:G:R little endian
        case bgr888 = 0x34324742
        /// 32-bit xBGR format, [31:0] x:B:G:R 8:8:8:8 little endian
        case xbgr8888 = 0x34324258
        /// 32-bit RGBx format, [31:0] R:G:B:x 8:8:8:8 little endian
        case rgbx8888 = 0x34325852
        /// 32-bit BGRx format, [31:0] B:G:R:x 8:8:8:8 little endian
        case bgrx8888 = 0x34325842
        /// 32-bit ABGR format, [31:0] A:B:G:R 8:8:8:8 little endian
        case abgr8888 = 0x34324241
        /// 32-bit RGBA format, [31:0] R:G:B:A 8:8:8:8 little endian
        case rgba8888 = 0x34324152
        /// 32-bit BGRA format, [31:0] B:G:R:A 8:8:8:8 little endian
        case bgra8888 = 0x34324142
        /// 32-bit xRGB format, [31:0] x:R:G:B 2:10:10:10 little endian
        case xrgb2101010 = 0x30335258
        /// 32-bit xBGR format, [31:0] x:B:G:R 2:10:10:10 little endian
        case xbgr2101010 = 0x30334258
        /// 32-bit RGBx format, [31:0] R:G:B:x 10:10:10:2 little endian
        case rgbx1010102 = 0x30335852
        /// 32-bit BGRx format, [31:0] B:G:R:x 10:10:10:2 little endian
        case bgrx1010102 = 0x30335842
        /// 32-bit ARGB format, [31:0] A:R:G:B 2:10:10:10 little endian
        case argb2101010 = 0x30335241
        /// 32-bit ABGR format, [31:0] A:B:G:R 2:10:10:10 little endian
        case abgr2101010 = 0x30334241
        /// 32-bit RGBA format, [31:0] R:G:B:A 10:10:10:2 little endian
        case rgba1010102 = 0x30334152
        /// 32-bit BGRA format, [31:0] B:G:R:A 10:10:10:2 little endian
        case bgra1010102 = 0x30334142
        /// packed YCbCr format, [31:0] Cr0:Y1:Cb0:Y0 8:8:8:8 little endian
        case yuyv = 0x56595559
        /// packed YCbCr format, [31:0] Cb0:Y1:Cr0:Y0 8:8:8:8 little endian
        case yvyu = 0x55595659
        /// packed YCbCr format, [31:0] Y1:Cr0:Y0:Cb0 8:8:8:8 little endian
        case uyvy = 0x59565955
        /// packed YCbCr format, [31:0] Y1:Cb0:Y0:Cr0 8:8:8:8 little endian
        case vyuy = 0x59555956
        /// packed AYCbCr format, [31:0] A:Y:Cb:Cr 8:8:8:8 little endian
        case ayuv = 0x56555941
        /// 2 plane YCbCr Cr:Cb format, 2x2 subsampled Cr:Cb plane
        case nv12 = 0x3231564e
        /// 2 plane YCbCr Cb:Cr format, 2x2 subsampled Cb:Cr plane
        case nv21 = 0x3132564e
        /// 2 plane YCbCr Cr:Cb format, 2x1 subsampled Cr:Cb plane
        case nv16 = 0x3631564e
        /// 2 plane YCbCr Cb:Cr format, 2x1 subsampled Cb:Cr plane
        case nv61 = 0x3136564e
        /// 3 plane YCbCr format, 4x4 subsampled Cb (1) and Cr (2) planes
        case yuv410 = 0x39565559
        /// 3 plane YCbCr format, 4x4 subsampled Cr (1) and Cb (2) planes
        case yvu410 = 0x39555659
        /// 3 plane YCbCr format, 4x1 subsampled Cb (1) and Cr (2) planes
        case yuv411 = 0x31315559
        /// 3 plane YCbCr format, 4x1 subsampled Cr (1) and Cb (2) planes
        case yvu411 = 0x31315659
        /// 3 plane YCbCr format, 2x2 subsampled Cb (1) and Cr (2) planes
        case yuv420 = 0x32315559
        /// 3 plane YCbCr format, 2x2 subsampled Cr (1) and Cb (2) planes
        case yvu420 = 0x32315659
        /// 3 plane YCbCr format, 2x1 subsampled Cb (1) and Cr (2) planes
        case yuv422 = 0x36315559
        /// 3 plane YCbCr format, 2x1 subsampled Cr (1) and Cb (2) planes
        case yvu422 = 0x36315659
        /// 3 plane YCbCr format, non-subsampled Cb (1) and Cr (2) planes
        case yuv444 = 0x34325559
        /// 3 plane YCbCr format, non-subsampled Cr (1) and Cb (2) planes
        case yvu444 = 0x34325659
        /// [7:0] R
        case r8 = 0x20203852
        /// [15:0] R little endian
        case r16 = 0x20363152
        /// [15:0] R:G 8:8 little endian
        case rg88 = 0x38384752
        /// [15:0] G:R 8:8 little endian
        case gr88 = 0x38385247
        /// [31:0] R:G 16:16 little endian
        case rg1616 = 0x32334752
        /// [31:0] G:R 16:16 little endian
        case gr1616 = 0x32335247
        /// [63:0] x:R:G:B 16:16:16:16 little endian
        case xrgb16161616f = 0x48345258
        /// [63:0] x:B:G:R 16:16:16:16 little endian
        case xbgr16161616f = 0x48344258
        /// [63:0] A:R:G:B 16:16:16:16 little endian
        case argb16161616f = 0x48345241
        /// [63:0] A:B:G:R 16:16:16:16 little endian
        case abgr16161616f = 0x48344241
        /// [31:0] X:Y:Cb:Cr 8:8:8:8 little endian
        case xyuv8888 = 0x56555958
        /// [23:0] Cr:Cb:Y 8:8:8 little endian
        case vuy888 = 0x34325556
        /// Y followed by U then V, 10:10:10. Non-linear modifier only
        case vuy101010 = 0x30335556
        /// [63:0] Cr0:0:Y1:0:Cb0:0:Y0:0 10:6:10:6:10:6:10:6 little endian per 2 Y pixels
        case y210 = 0x30313259
        /// [63:0] Cr0:0:Y1:0:Cb0:0:Y0:0 12:4:12:4:12:4:12:4 little endian per 2 Y pixels
        case y212 = 0x32313259
        /// [63:0] Cr0:Y1:Cb0:Y0 16:16:16:16 little endian per 2 Y pixels
        case y216 = 0x36313259
        /// [31:0] A:Cr:Y:Cb 2:10:10:10 little endian
        case y410 = 0x30313459
        /// [63:0] A:0:Cr:0:Y:0:Cb:0 12:4:12:4:12:4:12:4 little endian
        case y412 = 0x32313459
        /// [63:0] A:Cr:Y:Cb 16:16:16:16 little endian
        case y416 = 0x36313459
        /// [31:0] X:Cr:Y:Cb 2:10:10:10 little endian
        case xvyu2101010 = 0x30335658
        /// [63:0] X:0:Cr:0:Y:0:Cb:0 12:4:12:4:12:4:12:4 little endian
        case xvyu1216161616 = 0x36335658
        /// [63:0] X:Cr:Y:Cb 16:16:16:16 little endian
        case xvyu16161616 = 0x38345658
        /// [63:0]   A3:A2:Y3:0:Cr0:0:Y2:0:A1:A0:Y1:0:Cb0:0:Y0:0  1:1:8:2:8:2:8:2:1:1:8:2:8:2:8:2 little endian
        case y0l0 = 0x304c3059
        /// [63:0]   X3:X2:Y3:0:Cr0:0:Y2:0:X1:X0:Y1:0:Cb0:0:Y0:0  1:1:8:2:8:2:8:2:1:1:8:2:8:2:8:2 little endian
        case x0l0 = 0x304c3058
        /// [63:0]   A3:A2:Y3:Cr0:Y2:A1:A0:Y1:Cb0:Y0  1:1:10:10:10:1:1:10:10:10 little endian
        case y0l2 = 0x324c3059
        /// [63:0]   X3:X2:Y3:Cr0:Y2:X1:X0:Y1:Cb0:Y0  1:1:10:10:10:1:1:10:10:10 little endian
        case x0l2 = 0x324c3058
        case yuv4208bit = 0x38305559
        case yuv42010bit = 0x30315559
        case xrgb8888A8 = 0x38415258
        case xbgr8888A8 = 0x38414258
        case rgbx8888A8 = 0x38415852
        case bgrx8888A8 = 0x38415842
        case rgb888A8 = 0x38413852
        case bgr888A8 = 0x38413842
        case rgb565A8 = 0x38413552
        case bgr565A8 = 0x38413542
        /// non-subsampled Cr:Cb plane
        case nv24 = 0x3432564e
        /// non-subsampled Cb:Cr plane
        case nv42 = 0x3234564e
        /// 2x1 subsampled Cr:Cb plane, 10 bit per channel
        case p210 = 0x30313250
        /// 2x2 subsampled Cr:Cb plane 10 bits per channel
        case p010 = 0x30313050
        /// 2x2 subsampled Cr:Cb plane 12 bits per channel
        case p012 = 0x32313050
        /// 2x2 subsampled Cr:Cb plane 16 bits per channel
        case p016 = 0x36313050
        /// [63:0] A:x:B:x:G:x:R:x 10:6:10:6:10:6:10:6 little endian
        case axbxgxrx106106106106 = 0x30314241
        /// 2x2 subsampled Cr:Cb plane
        case nv15 = 0x3531564e
        case q410 = 0x30313451
        case q401 = 0x31303451
        /// [63:0] x:R:G:B 16:16:16:16 little endian
        case xrgb16161616 = 0x38345258
        /// [63:0] x:B:G:R 16:16:16:16 little endian
        case xbgr16161616 = 0x38344258
        /// [63:0] A:R:G:B 16:16:16:16 little endian
        case argb16161616 = 0x38345241
        /// [63:0] A:B:G:R 16:16:16:16 little endian
        case abgr16161616 = 0x38344241
        /// [7:0] C0:C1:C2:C3:C4:C5:C6:C7 1:1:1:1:1:1:1:1 eight pixels/byte
        case c1 = 0x20203143
        /// [7:0] C0:C1:C2:C3 2:2:2:2 four pixels/byte
        case c2 = 0x20203243
        /// [7:0] C0:C1 4:4 two pixels/byte
        case c4 = 0x20203443
        /// [7:0] D0:D1:D2:D3:D4:D5:D6:D7 1:1:1:1:1:1:1:1 eight pixels/byte
        case d1 = 0x20203144
        /// [7:0] D0:D1:D2:D3 2:2:2:2 four pixels/byte
        case d2 = 0x20203244
        /// [7:0] D0:D1 4:4 two pixels/byte
        case d4 = 0x20203444
        /// [7:0] D
        case d8 = 0x20203844
        /// [7:0] R0:R1:R2:R3:R4:R5:R6:R7 1:1:1:1:1:1:1:1 eight pixels/byte
        case r1 = 0x20203152
        /// [7:0] R0:R1:R2:R3 2:2:2:2 four pixels/byte
        case r2 = 0x20203252
        /// [7:0] R0:R1 4:4 two pixels/byte
        case r4 = 0x20203452
        /// [15:0] x:R 6:10 little endian
        case r10 = 0x20303152
        /// [15:0] x:R 4:12 little endian
        case r12 = 0x20323152
        /// [31:0] A:Cr:Cb:Y 8:8:8:8 little endian
        case avuy8888 = 0x59555641
        /// [31:0] X:Cr:Cb:Y 8:8:8:8 little endian
        case xvuy8888 = 0x59555658
        /// 2x2 subsampled Cr:Cb plane 10 bits per channel packed
        case p030 = 0x30333050
        /// [47:0] R:G:B 16:16:16 little endian
        case rgb161616 = 0x38344752
        /// [47:0] B:G:R 16:16:16 little endian
        case bgr161616 = 0x38344742
        /// [15:0] R 16 little endian
        case r16f = 0x48202052
        /// [31:0] G:R 16:16 little endian
        case gr1616f = 0x48205247
        /// [47:0] B:G:R 16:16:16 little endian
        case bgr161616f = 0x48524742
        /// [31:0] R 32 little endian
        case r32f = 0x46202052
        /// [63:0] G:R 32:32 little endian
        case gr3232f = 0x46205247
        /// [95:0] B:G:R 32:32:32 little endian
        case bgr323232f = 0x46524742
        /// [127:0] A:B:G:R 32:32:32:32 little endian
        case abgr32323232f = 0x46384241
        /// 2x1 subsampled Cr:Cb plane
        case nv20 = 0x3032564e
        /// non-subsampled Cr:Cb plane
        case nv30 = 0x3033564e
        /// 2x2 subsampled Cb (1) and Cr (2) planes 10 bits per channel
        case s010 = 0x30313053
        /// 2x1 subsampled Cb (1) and Cr (2) planes 10 bits per channel
        case s210 = 0x30313253
        /// non-subsampled Cb (1) and Cr (2) planes 10 bits per channel
        case s410 = 0x30313453
        /// 2x2 subsampled Cb (1) and Cr (2) planes 12 bits per channel
        case s012 = 0x32313053
        /// 2x1 subsampled Cb (1) and Cr (2) planes 12 bits per channel
        case s212 = 0x32313253
        /// non-subsampled Cb (1) and Cr (2) planes 12 bits per channel
        case s412 = 0x32313453
        /// 2x2 subsampled Cb (1) and Cr (2) planes 16 bits per channel
        case s016 = 0x36313053
        /// 2x1 subsampled Cb (1) and Cr (2) planes 16 bits per channel
        case s216 = 0x36313253
        /// non-subsampled Cb (1) and Cr (2) planes 16 bits per channel
        case s416 = 0x36313453
        /// [31:0] x:Cr:Cb:Y 2:10:10:10 little endian
        case xvuy2101010 = 0x30335958
        /// 2x1 subsampled Cr:Cb plane 10 bits per channel packed
        case p230 = 0x30333250
        case t430 = 0x30333454
        /// 8-bit Y-only
        case y8 = 0x59455247
        /// [31:0] x:Y2:Y1:Y0 2:10:10:10 little endian
        case xyyy2101010 = 0x34415059
    }
}

extension Resource where I == WlShm {
    /// pixel format description
    public func sendFormat(format: UInt32) {
        guard var event = beginEvent(opcode: 0, since: 1) else { return }
        event.uint(format)
        send(event)
    }
}

/// wl_buffer: content for a wl_surface
public enum WlBuffer: Interface {
    public static let name = "wl_buffer"
    public static let version: UInt32 = 1

    public enum Request {
        /// destroy a buffer
        case destroy
    }

    public static func decode(opcode: UInt16, from message: inout MessageReader, version: UInt32) throws(ProtocolError) -> Request {
        switch opcode {
        case 0:
            return .destroy
        default:
            throw message.invalidOpcode(opcode)
        }
    }

    public static func isDestructor(opcode: UInt16) -> Bool {
        [0].contains(opcode)
    }
}

extension Resource where I == WlBuffer {
    /// compositor releases buffer
    public func sendRelease() {
        guard let event = beginEvent(opcode: 0, since: 1) else { return }
        send(event)
    }
}

/// wl_data_offer: offer to transfer data
public enum WlDataOffer: Interface {
    public static let name = "wl_data_offer"
    public static let version: UInt32 = 4

    public enum Request {
        /// accept one of the offered mime types
        case accept(serial: UInt32, mimeType: String?)
        /// request that the data is transferred
        case receive(mimeType: String, fd: Int32)
        /// destroy data offer
        case destroy
        /// the offer will no longer be used
        case finish
        /// set the available/preferred drag-and-drop actions
        case setActions(dndActions: UInt32, preferredAction: UInt32)
    }

    public static func decode(opcode: UInt16, from message: inout MessageReader, version: UInt32) throws(ProtocolError) -> Request {
        switch opcode {
        case 0:
            let serial = try message.uint()
            let mimeType = try message.optionalString()
            return .accept(serial: serial, mimeType: mimeType)
        case 1:
            let mimeType = try message.string()
            let fd = try message.fd()
            return .receive(mimeType: mimeType, fd: fd)
        case 2:
            return .destroy
        case 3:
            guard version >= 3 else { throw message.invalidOpcode(opcode) }
            return .finish
        case 4:
            guard version >= 3 else { throw message.invalidOpcode(opcode) }
            let dndActions = try message.uint()
            let preferredAction = try message.uint()
            return .setActions(dndActions: dndActions, preferredAction: preferredAction)
        default:
            throw message.invalidOpcode(opcode)
        }
    }

    public static func isDestructor(opcode: UInt16) -> Bool {
        [2].contains(opcode)
    }

    public enum ErrorCode: UInt32, Sendable {
        /// finish request was called untimely
        case invalidFinish = 0
        /// action mask contains invalid values
        case invalidActionMask = 1
        /// action argument has an invalid value
        case invalidAction = 2
        /// offer doesn't accept this request
        case invalidOffer = 3
    }
}

extension Resource where I == WlDataOffer {
    /// advertise offered mime type
    public func sendOffer(mimeType: String) {
        guard var event = beginEvent(opcode: 0, since: 1) else { return }
        event.string(mimeType)
        send(event)
    }

    /// notify the source-side available actions
    public func sendSourceActions(sourceActions: UInt32) {
        guard var event = beginEvent(opcode: 1, since: 3) else { return }
        event.uint(sourceActions)
        send(event)
    }

    /// notify the selected action
    public func sendAction(dndAction: UInt32) {
        guard var event = beginEvent(opcode: 2, since: 3) else { return }
        event.uint(dndAction)
        send(event)
    }
}

/// wl_data_source: offer to transfer data
public enum WlDataSource: Interface {
    public static let name = "wl_data_source"
    public static let version: UInt32 = 4

    public enum Request {
        /// add an offered mime type
        case offer(mimeType: String)
        /// destroy the data source
        case destroy
        /// set the available drag-and-drop actions
        case setActions(dndActions: UInt32)
    }

    public static func decode(opcode: UInt16, from message: inout MessageReader, version: UInt32) throws(ProtocolError) -> Request {
        switch opcode {
        case 0:
            let mimeType = try message.string()
            return .offer(mimeType: mimeType)
        case 1:
            return .destroy
        case 2:
            guard version >= 3 else { throw message.invalidOpcode(opcode) }
            let dndActions = try message.uint()
            return .setActions(dndActions: dndActions)
        default:
            throw message.invalidOpcode(opcode)
        }
    }

    public static func isDestructor(opcode: UInt16) -> Bool {
        [1].contains(opcode)
    }

    public enum ErrorCode: UInt32, Sendable {
        /// action mask contains invalid values
        case invalidActionMask = 0
        /// source doesn't accept this request
        case invalidSource = 1
    }
}

extension Resource where I == WlDataSource {
    /// a target accepts an offered mime type
    public func sendTarget(mimeType: String?) {
        guard var event = beginEvent(opcode: 0, since: 1) else { return }
        event.string(mimeType)
        send(event)
    }

    /// send the data
    public func sendSend(mimeType: String, fd: Int32) {
        guard var event = beginEvent(opcode: 1, since: 1) else { return }
        event.string(mimeType)
        event.fd(fd)
        send(event)
    }

    /// selection was cancelled
    public func sendCancelled() {
        guard let event = beginEvent(opcode: 2, since: 1) else { return }
        send(event)
    }

    /// the drag-and-drop operation physically finished
    public func sendDndDropPerformed() {
        guard let event = beginEvent(opcode: 3, since: 3) else { return }
        send(event)
    }

    /// the drag-and-drop operation concluded
    public func sendDndFinished() {
        guard let event = beginEvent(opcode: 4, since: 3) else { return }
        send(event)
    }

    /// notify the selected action
    public func sendAction(dndAction: UInt32) {
        guard var event = beginEvent(opcode: 5, since: 3) else { return }
        event.uint(dndAction)
        send(event)
    }
}

/// wl_data_device: data transfer device
public enum WlDataDevice: Interface {
    public static let name = "wl_data_device"
    public static let version: UInt32 = 4

    public enum Request {
        /// start drag-and-drop operation
        case startDrag(source: Resource<WlDataSource>?, origin: Resource<WlSurface>, icon: Resource<WlSurface>?, serial: UInt32)
        /// copy data to the selection
        case setSelection(source: Resource<WlDataSource>?, serial: UInt32)
        /// destroy data device
        case release
    }

    public static func decode(opcode: UInt16, from message: inout MessageReader, version: UInt32) throws(ProtocolError) -> Request {
        switch opcode {
        case 0:
            let source = try message.optionalObject(WlDataSource.self)
            let origin = try message.object(WlSurface.self)
            let icon = try message.optionalObject(WlSurface.self)
            let serial = try message.uint()
            return .startDrag(source: source, origin: origin, icon: icon, serial: serial)
        case 1:
            let source = try message.optionalObject(WlDataSource.self)
            let serial = try message.uint()
            return .setSelection(source: source, serial: serial)
        case 2:
            guard version >= 2 else { throw message.invalidOpcode(opcode) }
            return .release
        default:
            throw message.invalidOpcode(opcode)
        }
    }

    public static func isDestructor(opcode: UInt16) -> Bool {
        [2].contains(opcode)
    }

    public enum ErrorCode: UInt32, Sendable {
        /// given wl_surface has another role
        case role = 0
        /// source has already been used
        case usedSource = 1
    }
}

extension Resource where I == WlDataDevice {
    /// introduce a new wl_data_offer
    public func sendDataOffer(id: Resource<WlDataOffer>) {
        guard var event = beginEvent(opcode: 0, since: 1) else { return }
        event.newID(id)
        send(event)
    }

    /// initiate drag-and-drop session
    public func sendEnter(serial: UInt32, surface: Resource<WlSurface>, x: Double, y: Double, id: Resource<WlDataOffer>?) {
        guard var event = beginEvent(opcode: 1, since: 1) else { return }
        event.uint(serial)
        event.object(surface)
        event.fixed(x)
        event.fixed(y)
        event.object(id)
        send(event)
    }

    /// end drag-and-drop session
    public func sendLeave() {
        guard let event = beginEvent(opcode: 2, since: 1) else { return }
        send(event)
    }

    /// drag-and-drop session motion
    public func sendMotion(time: UInt32, x: Double, y: Double) {
        guard var event = beginEvent(opcode: 3, since: 1) else { return }
        event.uint(time)
        event.fixed(x)
        event.fixed(y)
        send(event)
    }

    /// end drag-and-drop session successfully
    public func sendDrop() {
        guard let event = beginEvent(opcode: 4, since: 1) else { return }
        send(event)
    }

    /// advertise new selection
    public func sendSelection(id: Resource<WlDataOffer>?) {
        guard var event = beginEvent(opcode: 5, since: 1) else { return }
        event.object(id)
        send(event)
    }
}

/// wl_data_device_manager: data transfer interface
public enum WlDataDeviceManager: Interface {
    public static let name = "wl_data_device_manager"
    public static let version: UInt32 = 4

    public enum Request {
        /// create a new data source
        case createDataSource(id: NewID<WlDataSource>)
        /// create a new data device
        case getDataDevice(id: NewID<WlDataDevice>, seat: Resource<WlSeat>)
        /// destroy wl_data_device_manager
        case release
    }

    public static func decode(opcode: UInt16, from message: inout MessageReader, version: UInt32) throws(ProtocolError) -> Request {
        switch opcode {
        case 0:
            let id = try message.newID(WlDataSource.self, version: version)
            return .createDataSource(id: id)
        case 1:
            let id = try message.newID(WlDataDevice.self, version: version)
            let seat = try message.object(WlSeat.self)
            return .getDataDevice(id: id, seat: seat)
        case 2:
            guard version >= 4 else { throw message.invalidOpcode(opcode) }
            return .release
        default:
            throw message.invalidOpcode(opcode)
        }
    }

    public static func isDestructor(opcode: UInt16) -> Bool {
        [2].contains(opcode)
    }

    /// drag and drop actions
    public struct DndAction: OptionSet, Sendable {
        public let rawValue: UInt32
        public init(rawValue: UInt32) { self.rawValue = rawValue }
        /// copy action
        public static let copy = DndAction(rawValue: 1)
        /// move action
        public static let move = DndAction(rawValue: 2)
        /// ask action
        public static let ask = DndAction(rawValue: 4)
    }
}

/// wl_shell: create desktop-style surfaces
public enum WlShell: Interface {
    public static let name = "wl_shell"
    public static let version: UInt32 = 1

    public enum Request {
        /// create a shell surface from a surface
        case getShellSurface(id: NewID<WlShellSurface>, surface: Resource<WlSurface>)
    }

    public static func decode(opcode: UInt16, from message: inout MessageReader, version: UInt32) throws(ProtocolError) -> Request {
        switch opcode {
        case 0:
            let id = try message.newID(WlShellSurface.self, version: version)
            let surface = try message.object(WlSurface.self)
            return .getShellSurface(id: id, surface: surface)
        default:
            throw message.invalidOpcode(opcode)
        }
    }

    public static func isDestructor(opcode: UInt16) -> Bool {
        false
    }

    public enum ErrorCode: UInt32, Sendable {
        /// given wl_surface has another role
        case role = 0
    }
}

/// wl_shell_surface: desktop-style metadata interface
public enum WlShellSurface: Interface {
    public static let name = "wl_shell_surface"
    public static let version: UInt32 = 1

    public enum Request {
        /// respond to a ping event
        case pong(serial: UInt32)
        /// start an interactive move
        case move(seat: Resource<WlSeat>, serial: UInt32)
        /// start an interactive resize
        case resize(seat: Resource<WlSeat>, serial: UInt32, edges: UInt32)
        /// make the surface a toplevel surface
        case setToplevel
        /// make the surface a transient surface
        case setTransient(parent: Resource<WlSurface>, x: Int32, y: Int32, flags: UInt32)
        /// make the surface a fullscreen surface
        case setFullscreen(method: UInt32, framerate: UInt32, output: Resource<WlOutput>?)
        /// make the surface a popup surface
        case setPopup(seat: Resource<WlSeat>, serial: UInt32, parent: Resource<WlSurface>, x: Int32, y: Int32, flags: UInt32)
        /// make the surface a maximized surface
        case setMaximized(output: Resource<WlOutput>?)
        /// set surface title
        case setTitle(title: String)
        /// set surface class
        case setClass(class: String)
    }

    public static func decode(opcode: UInt16, from message: inout MessageReader, version: UInt32) throws(ProtocolError) -> Request {
        switch opcode {
        case 0:
            let serial = try message.uint()
            return .pong(serial: serial)
        case 1:
            let seat = try message.object(WlSeat.self)
            let serial = try message.uint()
            return .move(seat: seat, serial: serial)
        case 2:
            let seat = try message.object(WlSeat.self)
            let serial = try message.uint()
            let edges = try message.uint()
            return .resize(seat: seat, serial: serial, edges: edges)
        case 3:
            return .setToplevel
        case 4:
            let parent = try message.object(WlSurface.self)
            let x = try message.int()
            let y = try message.int()
            let flags = try message.uint()
            return .setTransient(parent: parent, x: x, y: y, flags: flags)
        case 5:
            let method = try message.uint()
            let framerate = try message.uint()
            let output = try message.optionalObject(WlOutput.self)
            return .setFullscreen(method: method, framerate: framerate, output: output)
        case 6:
            let seat = try message.object(WlSeat.self)
            let serial = try message.uint()
            let parent = try message.object(WlSurface.self)
            let x = try message.int()
            let y = try message.int()
            let flags = try message.uint()
            return .setPopup(seat: seat, serial: serial, parent: parent, x: x, y: y, flags: flags)
        case 7:
            let output = try message.optionalObject(WlOutput.self)
            return .setMaximized(output: output)
        case 8:
            let title = try message.string()
            return .setTitle(title: title)
        case 9:
            let `class` = try message.string()
            return .setClass(class: `class`)
        default:
            throw message.invalidOpcode(opcode)
        }
    }

    public static func isDestructor(opcode: UInt16) -> Bool {
        false
    }

    /// edge values for resizing
    public struct Resize: OptionSet, Sendable {
        public let rawValue: UInt32
        public init(rawValue: UInt32) { self.rawValue = rawValue }
        /// top edge
        public static let top = Resize(rawValue: 1)
        /// bottom edge
        public static let bottom = Resize(rawValue: 2)
        /// left edge
        public static let left = Resize(rawValue: 4)
        /// top and left edges
        public static let topLeft = Resize(rawValue: 5)
        /// bottom and left edges
        public static let bottomLeft = Resize(rawValue: 6)
        /// right edge
        public static let right = Resize(rawValue: 8)
        /// top and right edges
        public static let topRight = Resize(rawValue: 9)
        /// bottom and right edges
        public static let bottomRight = Resize(rawValue: 10)
    }

    /// details of transient behaviour
    public struct Transient: OptionSet, Sendable {
        public let rawValue: UInt32
        public init(rawValue: UInt32) { self.rawValue = rawValue }
        /// do not set keyboard focus
        public static let inactive = Transient(rawValue: 0x1)
    }

    /// different method to set the surface fullscreen
    public enum FullscreenMethod: UInt32, Sendable {
        /// no preference, apply default policy
        case `default` = 0
        /// scale, preserve the surface's aspect ratio and center on output
        case scale = 1
        /// switch output mode to the smallest mode that can fit the surface, add black borders to compensate size mismatch
        case driver = 2
        /// no upscaling, center on output and add black borders to compensate size mismatch
        case fill = 3
    }
}

extension Resource where I == WlShellSurface {
    /// ping client
    public func sendPing(serial: UInt32) {
        guard var event = beginEvent(opcode: 0, since: 1) else { return }
        event.uint(serial)
        send(event)
    }

    /// suggest resize
    public func sendConfigure(edges: UInt32, width: Int32, height: Int32) {
        guard var event = beginEvent(opcode: 1, since: 1) else { return }
        event.uint(edges)
        event.int(width)
        event.int(height)
        send(event)
    }

    /// popup interaction is done
    public func sendPopupDone() {
        guard let event = beginEvent(opcode: 2, since: 1) else { return }
        send(event)
    }
}

/// wl_surface: an onscreen surface
public enum WlSurface: Interface {
    public static let name = "wl_surface"
    public static let version: UInt32 = 7

    public enum Request {
        /// delete surface
        case destroy
        /// set the surface contents
        case attach(buffer: Resource<WlBuffer>?, x: Int32, y: Int32)
        /// mark part of the surface damaged
        case damage(x: Int32, y: Int32, width: Int32, height: Int32)
        /// request a frame throttling hint
        case frame(callback: NewID<WlCallback>)
        /// set opaque region
        case setOpaqueRegion(region: Resource<WlRegion>?)
        /// set input region
        case setInputRegion(region: Resource<WlRegion>?)
        /// commit pending surface state
        case commit
        /// sets the buffer transformation
        case setBufferTransform(transform: Int32)
        /// sets the buffer scaling factor
        case setBufferScale(scale: Int32)
        /// mark part of the surface damaged using buffer coordinates
        case damageBuffer(x: Int32, y: Int32, width: Int32, height: Int32)
        /// set the surface contents offset
        case offset(x: Int32, y: Int32)
        /// get a release callback
        case getRelease(callback: NewID<WlCallback>)
    }

    public static func decode(opcode: UInt16, from message: inout MessageReader, version: UInt32) throws(ProtocolError) -> Request {
        switch opcode {
        case 0:
            return .destroy
        case 1:
            let buffer = try message.optionalObject(WlBuffer.self)
            let x = try message.int()
            let y = try message.int()
            return .attach(buffer: buffer, x: x, y: y)
        case 2:
            let x = try message.int()
            let y = try message.int()
            let width = try message.int()
            let height = try message.int()
            return .damage(x: x, y: y, width: width, height: height)
        case 3:
            let callback = try message.newID(WlCallback.self, version: version)
            return .frame(callback: callback)
        case 4:
            let region = try message.optionalObject(WlRegion.self)
            return .setOpaqueRegion(region: region)
        case 5:
            let region = try message.optionalObject(WlRegion.self)
            return .setInputRegion(region: region)
        case 6:
            return .commit
        case 7:
            guard version >= 2 else { throw message.invalidOpcode(opcode) }
            let transform = try message.int()
            return .setBufferTransform(transform: transform)
        case 8:
            guard version >= 3 else { throw message.invalidOpcode(opcode) }
            let scale = try message.int()
            return .setBufferScale(scale: scale)
        case 9:
            guard version >= 4 else { throw message.invalidOpcode(opcode) }
            let x = try message.int()
            let y = try message.int()
            let width = try message.int()
            let height = try message.int()
            return .damageBuffer(x: x, y: y, width: width, height: height)
        case 10:
            guard version >= 5 else { throw message.invalidOpcode(opcode) }
            let x = try message.int()
            let y = try message.int()
            return .offset(x: x, y: y)
        case 11:
            guard version >= 7 else { throw message.invalidOpcode(opcode) }
            let callback = try message.newID(WlCallback.self, version: version)
            return .getRelease(callback: callback)
        default:
            throw message.invalidOpcode(opcode)
        }
    }

    public static func isDestructor(opcode: UInt16) -> Bool {
        [0].contains(opcode)
    }

    /// wl_surface error values
    public enum ErrorCode: UInt32, Sendable {
        /// buffer scale value is invalid
        case invalidScale = 0
        /// buffer transform value is invalid
        case invalidTransform = 1
        /// buffer size is invalid
        case invalidSize = 2
        /// buffer offset is invalid
        case invalidOffset = 3
        /// surface was destroyed before its role object
        case defunctRoleObject = 4
        /// no buffer was attached
        case noBuffer = 5
    }
}

extension Resource where I == WlSurface {
    /// surface enters an output
    public func sendEnter(output: Resource<WlOutput>) {
        guard var event = beginEvent(opcode: 0, since: 1) else { return }
        event.object(output)
        send(event)
    }

    /// surface leaves an output
    public func sendLeave(output: Resource<WlOutput>) {
        guard var event = beginEvent(opcode: 1, since: 1) else { return }
        event.object(output)
        send(event)
    }

    /// preferred buffer scale for the surface
    public func sendPreferredBufferScale(factor: Int32) {
        guard var event = beginEvent(opcode: 2, since: 6) else { return }
        event.int(factor)
        send(event)
    }

    /// preferred buffer transform for the surface
    public func sendPreferredBufferTransform(transform: UInt32) {
        guard var event = beginEvent(opcode: 3, since: 6) else { return }
        event.uint(transform)
        send(event)
    }
}

/// wl_seat: group of input devices
public enum WlSeat: Interface {
    public static let name = "wl_seat"
    public static let version: UInt32 = 11

    public enum Request {
        /// return pointer object
        case getPointer(id: NewID<WlPointer>)
        /// return keyboard object
        case getKeyboard(id: NewID<WlKeyboard>)
        /// return touch object
        case getTouch(id: NewID<WlTouch>)
        /// release the seat object
        case release
    }

    public static func decode(opcode: UInt16, from message: inout MessageReader, version: UInt32) throws(ProtocolError) -> Request {
        switch opcode {
        case 0:
            let id = try message.newID(WlPointer.self, version: version)
            return .getPointer(id: id)
        case 1:
            let id = try message.newID(WlKeyboard.self, version: version)
            return .getKeyboard(id: id)
        case 2:
            let id = try message.newID(WlTouch.self, version: version)
            return .getTouch(id: id)
        case 3:
            guard version >= 5 else { throw message.invalidOpcode(opcode) }
            return .release
        default:
            throw message.invalidOpcode(opcode)
        }
    }

    public static func isDestructor(opcode: UInt16) -> Bool {
        [3].contains(opcode)
    }

    /// seat capability bitmask
    public struct Capability: OptionSet, Sendable {
        public let rawValue: UInt32
        public init(rawValue: UInt32) { self.rawValue = rawValue }
        /// the seat has pointer devices
        public static let pointer = Capability(rawValue: 1)
        /// the seat has one or more keyboards
        public static let keyboard = Capability(rawValue: 2)
        /// the seat has touch devices
        public static let touch = Capability(rawValue: 4)
    }

    /// wl_seat error values
    public enum ErrorCode: UInt32, Sendable {
        /// get_pointer, get_keyboard or get_touch called on seat without the matching capability
        case missingCapability = 0
    }
}

extension Resource where I == WlSeat {
    /// seat capabilities changed
    public func sendCapabilities(capabilities: UInt32) {
        guard var event = beginEvent(opcode: 0, since: 1) else { return }
        event.uint(capabilities)
        send(event)
    }

    /// unique identifier for this seat
    public func sendName(name: String) {
        guard var event = beginEvent(opcode: 1, since: 2) else { return }
        event.string(name)
        send(event)
    }
}

/// wl_pointer: pointer input device
public enum WlPointer: Interface {
    public static let name = "wl_pointer"
    public static let version: UInt32 = 11

    public enum Request {
        /// set the pointer surface
        case setCursor(serial: UInt32, surface: Resource<WlSurface>?, hotspotX: Int32, hotspotY: Int32)
        /// release the pointer object
        case release
    }

    public static func decode(opcode: UInt16, from message: inout MessageReader, version: UInt32) throws(ProtocolError) -> Request {
        switch opcode {
        case 0:
            let serial = try message.uint()
            let surface = try message.optionalObject(WlSurface.self)
            let hotspotX = try message.int()
            let hotspotY = try message.int()
            return .setCursor(serial: serial, surface: surface, hotspotX: hotspotX, hotspotY: hotspotY)
        case 1:
            guard version >= 3 else { throw message.invalidOpcode(opcode) }
            return .release
        default:
            throw message.invalidOpcode(opcode)
        }
    }

    public static func isDestructor(opcode: UInt16) -> Bool {
        [1].contains(opcode)
    }

    public enum ErrorCode: UInt32, Sendable {
        /// given wl_surface has another role
        case role = 0
    }

    /// physical button state
    public enum ButtonState: UInt32, Sendable {
        /// the button is not pressed
        case released = 0
        /// the button is pressed
        case pressed = 1
    }

    /// axis types
    public enum Axis: UInt32, Sendable {
        /// vertical axis
        case verticalScroll = 0
        /// horizontal axis
        case horizontalScroll = 1
    }

    /// axis source types
    public enum AxisSource: UInt32, Sendable {
        /// a physical wheel rotation
        case wheel = 0
        /// finger on a touch surface
        case finger = 1
        /// continuous coordinate space
        case continuous = 2
        /// a physical wheel tilt
        case wheelTilt = 3
    }

    /// axis relative direction
    public enum AxisRelativeDirection: UInt32, Sendable {
        /// physical motion matches axis direction
        case identical = 0
        /// physical motion is the inverse of the axis direction
        case inverted = 1
    }
}

extension Resource where I == WlPointer {
    /// enter event
    public func sendEnter(serial: UInt32, surface: Resource<WlSurface>, surfaceX: Double, surfaceY: Double) {
        guard var event = beginEvent(opcode: 0, since: 1) else { return }
        event.uint(serial)
        event.object(surface)
        event.fixed(surfaceX)
        event.fixed(surfaceY)
        send(event)
    }

    /// leave event
    public func sendLeave(serial: UInt32, surface: Resource<WlSurface>) {
        guard var event = beginEvent(opcode: 1, since: 1) else { return }
        event.uint(serial)
        event.object(surface)
        send(event)
    }

    /// pointer motion event
    public func sendMotion(time: UInt32, surfaceX: Double, surfaceY: Double) {
        guard var event = beginEvent(opcode: 2, since: 1) else { return }
        event.uint(time)
        event.fixed(surfaceX)
        event.fixed(surfaceY)
        send(event)
    }

    /// pointer button event
    public func sendButton(serial: UInt32, time: UInt32, button: UInt32, state: UInt32) {
        guard var event = beginEvent(opcode: 3, since: 1) else { return }
        event.uint(serial)
        event.uint(time)
        event.uint(button)
        event.uint(state)
        send(event)
    }

    /// axis event
    public func sendAxis(time: UInt32, axis: UInt32, value: Double) {
        guard var event = beginEvent(opcode: 4, since: 1) else { return }
        event.uint(time)
        event.uint(axis)
        event.fixed(value)
        send(event)
    }

    /// end of a pointer event sequence
    public func sendFrame() {
        guard let event = beginEvent(opcode: 5, since: 5) else { return }
        send(event)
    }

    /// axis source event
    public func sendAxisSource(axisSource: UInt32) {
        guard var event = beginEvent(opcode: 6, since: 5) else { return }
        event.uint(axisSource)
        send(event)
    }

    /// axis stop event
    public func sendAxisStop(time: UInt32, axis: UInt32) {
        guard var event = beginEvent(opcode: 7, since: 5) else { return }
        event.uint(time)
        event.uint(axis)
        send(event)
    }

    /// axis click event
    public func sendAxisDiscrete(axis: UInt32, discrete: Int32) {
        guard var event = beginEvent(opcode: 8, since: 5) else { return }
        event.uint(axis)
        event.int(discrete)
        send(event)
    }

    /// axis high-resolution scroll event
    public func sendAxisValue120(axis: UInt32, value120: Int32) {
        guard var event = beginEvent(opcode: 9, since: 8) else { return }
        event.uint(axis)
        event.int(value120)
        send(event)
    }

    /// axis relative physical direction event
    public func sendAxisRelativeDirection(axis: UInt32, direction: UInt32) {
        guard var event = beginEvent(opcode: 10, since: 9) else { return }
        event.uint(axis)
        event.uint(direction)
        send(event)
    }

    /// pointer warp event
    public func sendWarp(surfaceX: Double, surfaceY: Double) {
        guard var event = beginEvent(opcode: 11, since: 11) else { return }
        event.fixed(surfaceX)
        event.fixed(surfaceY)
        send(event)
    }
}

/// wl_keyboard: keyboard input device
public enum WlKeyboard: Interface {
    public static let name = "wl_keyboard"
    public static let version: UInt32 = 11

    public enum Request {
        /// release the keyboard object
        case release
    }

    public static func decode(opcode: UInt16, from message: inout MessageReader, version: UInt32) throws(ProtocolError) -> Request {
        switch opcode {
        case 0:
            guard version >= 3 else { throw message.invalidOpcode(opcode) }
            return .release
        default:
            throw message.invalidOpcode(opcode)
        }
    }

    public static func isDestructor(opcode: UInt16) -> Bool {
        [0].contains(opcode)
    }

    /// keyboard mapping format
    public enum KeymapFormat: UInt32, Sendable {
        /// no keymap; client must understand how to interpret the raw keycode
        case noKeymap = 0
        /// libxkbcommon compatible, null-terminated string; to determine the xkb keycode, clients must add 8 to the key event keycode
        case xkbV1 = 1
    }

    /// physical key state
    public enum KeyState: UInt32, Sendable {
        /// key is not pressed
        case released = 0
        /// key is pressed
        case pressed = 1
        /// key was repeated
        case repeated = 2
    }
}

extension Resource where I == WlKeyboard {
    /// keyboard mapping
    public func sendKeymap(format: UInt32, fd: Int32, size: UInt32) {
        guard var event = beginEvent(opcode: 0, since: 1) else { return }
        event.uint(format)
        event.fd(fd)
        event.uint(size)
        send(event)
    }

    /// enter event
    public func sendEnter(serial: UInt32, surface: Resource<WlSurface>, keys: [UInt8]) {
        guard var event = beginEvent(opcode: 1, since: 1) else { return }
        event.uint(serial)
        event.object(surface)
        event.array(keys)
        send(event)
    }

    /// leave event
    public func sendLeave(serial: UInt32, surface: Resource<WlSurface>) {
        guard var event = beginEvent(opcode: 2, since: 1) else { return }
        event.uint(serial)
        event.object(surface)
        send(event)
    }

    /// key event
    public func sendKey(serial: UInt32, time: UInt32, key: UInt32, state: UInt32) {
        guard var event = beginEvent(opcode: 3, since: 1) else { return }
        event.uint(serial)
        event.uint(time)
        event.uint(key)
        event.uint(state)
        send(event)
    }

    /// modifier and group state
    public func sendModifiers(serial: UInt32, modsDepressed: UInt32, modsLatched: UInt32, modsLocked: UInt32, group: UInt32) {
        guard var event = beginEvent(opcode: 4, since: 1) else { return }
        event.uint(serial)
        event.uint(modsDepressed)
        event.uint(modsLatched)
        event.uint(modsLocked)
        event.uint(group)
        send(event)
    }

    /// repeat rate and delay
    public func sendRepeatInfo(rate: Int32, delay: Int32) {
        guard var event = beginEvent(opcode: 5, since: 4) else { return }
        event.int(rate)
        event.int(delay)
        send(event)
    }
}

/// wl_touch: touchscreen input device
public enum WlTouch: Interface {
    public static let name = "wl_touch"
    public static let version: UInt32 = 11

    public enum Request {
        /// release the touch object
        case release
    }

    public static func decode(opcode: UInt16, from message: inout MessageReader, version: UInt32) throws(ProtocolError) -> Request {
        switch opcode {
        case 0:
            guard version >= 3 else { throw message.invalidOpcode(opcode) }
            return .release
        default:
            throw message.invalidOpcode(opcode)
        }
    }

    public static func isDestructor(opcode: UInt16) -> Bool {
        [0].contains(opcode)
    }
}

extension Resource where I == WlTouch {
    /// touch down event and beginning of a touch sequence
    public func sendDown(serial: UInt32, time: UInt32, surface: Resource<WlSurface>, id: Int32, x: Double, y: Double) {
        guard var event = beginEvent(opcode: 0, since: 1) else { return }
        event.uint(serial)
        event.uint(time)
        event.object(surface)
        event.int(id)
        event.fixed(x)
        event.fixed(y)
        send(event)
    }

    /// end of a touch event sequence
    public func sendUp(serial: UInt32, time: UInt32, id: Int32) {
        guard var event = beginEvent(opcode: 1, since: 1) else { return }
        event.uint(serial)
        event.uint(time)
        event.int(id)
        send(event)
    }

    /// update of touch point coordinates
    public func sendMotion(time: UInt32, id: Int32, x: Double, y: Double) {
        guard var event = beginEvent(opcode: 2, since: 1) else { return }
        event.uint(time)
        event.int(id)
        event.fixed(x)
        event.fixed(y)
        send(event)
    }

    /// end of touch frame event
    public func sendFrame() {
        guard let event = beginEvent(opcode: 3, since: 1) else { return }
        send(event)
    }

    /// touch session cancelled
    public func sendCancel() {
        guard let event = beginEvent(opcode: 4, since: 1) else { return }
        send(event)
    }

    /// update shape of touch point
    public func sendShape(id: Int32, major: Double, minor: Double) {
        guard var event = beginEvent(opcode: 5, since: 6) else { return }
        event.int(id)
        event.fixed(major)
        event.fixed(minor)
        send(event)
    }

    /// update orientation of touch point
    public func sendOrientation(id: Int32, orientation: Double) {
        guard var event = beginEvent(opcode: 6, since: 6) else { return }
        event.int(id)
        event.fixed(orientation)
        send(event)
    }
}

/// wl_output: compositor output region
public enum WlOutput: Interface {
    public static let name = "wl_output"
    public static let version: UInt32 = 4

    public enum Request {
        /// release the output object
        case release
    }

    public static func decode(opcode: UInt16, from message: inout MessageReader, version: UInt32) throws(ProtocolError) -> Request {
        switch opcode {
        case 0:
            guard version >= 3 else { throw message.invalidOpcode(opcode) }
            return .release
        default:
            throw message.invalidOpcode(opcode)
        }
    }

    public static func isDestructor(opcode: UInt16) -> Bool {
        [0].contains(opcode)
    }

    /// subpixel geometry information
    public enum Subpixel: UInt32, Sendable {
        /// unknown geometry
        case unknown = 0
        /// no geometry
        case none = 1
        /// horizontal RGB
        case horizontalRgb = 2
        /// horizontal BGR
        case horizontalBgr = 3
        /// vertical RGB
        case verticalRgb = 4
        /// vertical BGR
        case verticalBgr = 5
    }

    /// transformation applied to buffer contents
    public enum Transform: UInt32, Sendable {
        /// no transform
        case normal = 0
        /// 90 degrees counter-clockwise
        case _90 = 1
        /// 180 degrees counter-clockwise
        case _180 = 2
        /// 270 degrees counter-clockwise
        case _270 = 3
        /// 180 degree flip around a vertical axis
        case flipped = 4
        /// flip and rotate 90 degrees counter-clockwise
        case flipped90 = 5
        /// flip and rotate 180 degrees counter-clockwise
        case flipped180 = 6
        /// flip and rotate 270 degrees counter-clockwise
        case flipped270 = 7
    }

    /// mode information
    public struct Mode: OptionSet, Sendable {
        public let rawValue: UInt32
        public init(rawValue: UInt32) { self.rawValue = rawValue }
        /// indicates this is the current mode
        public static let current = Mode(rawValue: 0x1)
        /// indicates this is the preferred mode
        public static let preferred = Mode(rawValue: 0x2)
    }
}

extension Resource where I == WlOutput {
    /// properties of the output
    public func sendGeometry(x: Int32, y: Int32, physicalWidth: Int32, physicalHeight: Int32, subpixel: Int32, make: String, model: String, transform: Int32) {
        guard var event = beginEvent(opcode: 0, since: 1) else { return }
        event.int(x)
        event.int(y)
        event.int(physicalWidth)
        event.int(physicalHeight)
        event.int(subpixel)
        event.string(make)
        event.string(model)
        event.int(transform)
        send(event)
    }

    /// advertise available modes for the output
    public func sendMode(flags: UInt32, width: Int32, height: Int32, refresh: Int32) {
        guard var event = beginEvent(opcode: 1, since: 1) else { return }
        event.uint(flags)
        event.int(width)
        event.int(height)
        event.int(refresh)
        send(event)
    }

    /// sent all information about output
    public func sendDone() {
        guard let event = beginEvent(opcode: 2, since: 2) else { return }
        send(event)
    }

    /// output scaling properties
    public func sendScale(factor: Int32) {
        guard var event = beginEvent(opcode: 3, since: 2) else { return }
        event.int(factor)
        send(event)
    }

    /// name of this output
    public func sendName(name: String) {
        guard var event = beginEvent(opcode: 4, since: 4) else { return }
        event.string(name)
        send(event)
    }

    /// human-readable description of this output
    public func sendDescription(description: String) {
        guard var event = beginEvent(opcode: 5, since: 4) else { return }
        event.string(description)
        send(event)
    }
}

/// wl_region: region interface
public enum WlRegion: Interface {
    public static let name = "wl_region"
    public static let version: UInt32 = 7

    public enum Request {
        /// destroy region
        case destroy
        /// add rectangle to region
        case add(x: Int32, y: Int32, width: Int32, height: Int32)
        /// subtract rectangle from region
        case subtract(x: Int32, y: Int32, width: Int32, height: Int32)
    }

    public static func decode(opcode: UInt16, from message: inout MessageReader, version: UInt32) throws(ProtocolError) -> Request {
        switch opcode {
        case 0:
            return .destroy
        case 1:
            let x = try message.int()
            let y = try message.int()
            let width = try message.int()
            let height = try message.int()
            return .add(x: x, y: y, width: width, height: height)
        case 2:
            let x = try message.int()
            let y = try message.int()
            let width = try message.int()
            let height = try message.int()
            return .subtract(x: x, y: y, width: width, height: height)
        default:
            throw message.invalidOpcode(opcode)
        }
    }

    public static func isDestructor(opcode: UInt16) -> Bool {
        [0].contains(opcode)
    }
}

/// wl_subcompositor: sub-surface compositing
public enum WlSubcompositor: Interface {
    public static let name = "wl_subcompositor"
    public static let version: UInt32 = 1

    public enum Request {
        /// unbind from the subcompositor interface
        case destroy
        /// give a surface the role sub-surface
        case getSubsurface(id: NewID<WlSubsurface>, surface: Resource<WlSurface>, parent: Resource<WlSurface>)
    }

    public static func decode(opcode: UInt16, from message: inout MessageReader, version: UInt32) throws(ProtocolError) -> Request {
        switch opcode {
        case 0:
            return .destroy
        case 1:
            let id = try message.newID(WlSubsurface.self, version: version)
            let surface = try message.object(WlSurface.self)
            let parent = try message.object(WlSurface.self)
            return .getSubsurface(id: id, surface: surface, parent: parent)
        default:
            throw message.invalidOpcode(opcode)
        }
    }

    public static func isDestructor(opcode: UInt16) -> Bool {
        [0].contains(opcode)
    }

    public enum ErrorCode: UInt32, Sendable {
        /// the to-be sub-surface is invalid
        case badSurface = 0
        /// the to-be sub-surface parent is invalid
        case badParent = 1
    }
}

/// wl_subsurface: sub-surface interface to a wl_surface
public enum WlSubsurface: Interface {
    public static let name = "wl_subsurface"
    public static let version: UInt32 = 1

    public enum Request {
        /// remove sub-surface interface
        case destroy
        /// reposition the sub-surface
        case setPosition(x: Int32, y: Int32)
        /// restack the sub-surface
        case placeAbove(sibling: Resource<WlSurface>)
        /// restack the sub-surface
        case placeBelow(sibling: Resource<WlSurface>)
        /// set sub-surface to synchronized mode
        case setSync
        /// set sub-surface to desynchronized mode
        case setDesync
    }

    public static func decode(opcode: UInt16, from message: inout MessageReader, version: UInt32) throws(ProtocolError) -> Request {
        switch opcode {
        case 0:
            return .destroy
        case 1:
            let x = try message.int()
            let y = try message.int()
            return .setPosition(x: x, y: y)
        case 2:
            let sibling = try message.object(WlSurface.self)
            return .placeAbove(sibling: sibling)
        case 3:
            let sibling = try message.object(WlSurface.self)
            return .placeBelow(sibling: sibling)
        case 4:
            return .setSync
        case 5:
            return .setDesync
        default:
            throw message.invalidOpcode(opcode)
        }
    }

    public static func isDestructor(opcode: UInt16) -> Bool {
        [0].contains(opcode)
    }

    public enum ErrorCode: UInt32, Sendable {
        /// wl_surface is not a sibling or the parent
        case badSurface = 0
    }
}

/// wl_fixes: wayland protocol fixes
public enum WlFixes: Interface {
    public static let name = "wl_fixes"
    public static let version: UInt32 = 2

    public enum Request {
        /// destroys this object
        case destroy
        /// destroy a wl_registry
        case destroyRegistry(registry: Resource<WlRegistry>)
        /// acknowledge global removal
        case ackGlobalRemove(registry: Resource<WlRegistry>, name: UInt32)
    }

    public static func decode(opcode: UInt16, from message: inout MessageReader, version: UInt32) throws(ProtocolError) -> Request {
        switch opcode {
        case 0:
            return .destroy
        case 1:
            let registry = try message.object(WlRegistry.self)
            return .destroyRegistry(registry: registry)
        case 2:
            guard version >= 2 else { throw message.invalidOpcode(opcode) }
            let registry = try message.object(WlRegistry.self)
            let name = try message.uint()
            return .ackGlobalRemove(registry: registry, name: name)
        default:
            throw message.invalidOpcode(opcode)
        }
    }

    public static func isDestructor(opcode: UInt16) -> Bool {
        [0].contains(opcode)
    }

    /// wl_fixes error values
    public enum ErrorCode: UInt32, Sendable {
        /// unknown global or the global is not removed
        case invalidAckRemove = 0
    }
}
