// Generated by wayland-swift-scanner from xdg-shell.xml. Do not edit.
// Regenerate with `make protocols`.

/// xdg_wm_base: create desktop-style surfaces
public enum XdgWmBase: Interface {
    public static let name = "xdg_wm_base"
    public static let version: UInt32 = 7

    public enum Request {
        /// destroy xdg_wm_base
        case destroy
        /// create a positioner object
        case createPositioner(id: NewID<XdgPositioner>)
        /// create a shell surface from a surface
        case getXdgSurface(id: NewID<XdgSurface>, surface: Resource<WlSurface>)
        /// respond to a ping event
        case pong(serial: UInt32)
    }

    public static func decode(opcode: UInt16, from message: inout MessageReader, version: UInt32) throws(ProtocolError) -> Request {
        switch opcode {
        case 0:
            return .destroy
        case 1:
            let id = try message.newID(XdgPositioner.self, version: version)
            return .createPositioner(id: id)
        case 2:
            let id = try message.newID(XdgSurface.self, version: version)
            let surface = try message.object(WlSurface.self)
            return .getXdgSurface(id: id, surface: surface)
        case 3:
            let serial = try message.uint()
            return .pong(serial: serial)
        default:
            throw message.invalidOpcode(opcode)
        }
    }

    public static func isDestructor(opcode: UInt16) -> Bool {
        [0].contains(opcode)
    }

    public enum ErrorCode: UInt32, Sendable {
        /// given wl_surface has another role
        case role = 0
        /// xdg_wm_base was destroyed before children
        case defunctSurfaces = 1
        /// the client tried to map or destroy a non-topmost popup
        case notTheTopmostPopup = 2
        /// the client specified an invalid popup parent surface
        case invalidPopupParent = 3
        /// the client provided an invalid surface state
        case invalidSurfaceState = 4
        /// the client provided an invalid positioner
        case invalidPositioner = 5
        /// the client didn’t respond to a ping event in time
        case unresponsive = 6
    }
}

extension Resource where I == XdgWmBase {
    /// check if the client is alive
    public func sendPing(serial: UInt32) {
        guard var event = beginEvent(opcode: 0, since: 1) else { return }
        event.uint(serial)
        send(event)
    }
}

/// xdg_positioner: child surface positioner
public enum XdgPositioner: Interface {
    public static let name = "xdg_positioner"
    public static let version: UInt32 = 7

    public enum Request {
        /// destroy the xdg_positioner object
        case destroy
        /// set the size of the to-be positioned rectangle
        case setSize(width: Int32, height: Int32)
        /// set the anchor rectangle within the parent surface
        case setAnchorRect(x: Int32, y: Int32, width: Int32, height: Int32)
        /// set anchor rectangle anchor
        case setAnchor(anchor: UInt32)
        /// set child surface gravity
        case setGravity(gravity: UInt32)
        /// set the adjustment to be done when constrained
        case setConstraintAdjustment(constraintAdjustment: UInt32)
        /// set surface position offset
        case setOffset(x: Int32, y: Int32)
        /// continuously reconstrain the surface
        case setReactive
        /// set parent size
        case setParentSize(parentWidth: Int32, parentHeight: Int32)
        /// set parent configure this is a response to
        case setParentConfigure(serial: UInt32)
    }

    public static func decode(opcode: UInt16, from message: inout MessageReader, version: UInt32) throws(ProtocolError) -> Request {
        switch opcode {
        case 0:
            return .destroy
        case 1:
            let width = try message.int()
            let height = try message.int()
            return .setSize(width: width, height: height)
        case 2:
            let x = try message.int()
            let y = try message.int()
            let width = try message.int()
            let height = try message.int()
            return .setAnchorRect(x: x, y: y, width: width, height: height)
        case 3:
            let anchor = try message.uint()
            return .setAnchor(anchor: anchor)
        case 4:
            let gravity = try message.uint()
            return .setGravity(gravity: gravity)
        case 5:
            let constraintAdjustment = try message.uint()
            return .setConstraintAdjustment(constraintAdjustment: constraintAdjustment)
        case 6:
            let x = try message.int()
            let y = try message.int()
            return .setOffset(x: x, y: y)
        case 7:
            guard version >= 3 else { throw message.invalidOpcode(opcode) }
            return .setReactive
        case 8:
            guard version >= 3 else { throw message.invalidOpcode(opcode) }
            let parentWidth = try message.int()
            let parentHeight = try message.int()
            return .setParentSize(parentWidth: parentWidth, parentHeight: parentHeight)
        case 9:
            guard version >= 3 else { throw message.invalidOpcode(opcode) }
            let serial = try message.uint()
            return .setParentConfigure(serial: serial)
        default:
            throw message.invalidOpcode(opcode)
        }
    }

    public static func isDestructor(opcode: UInt16) -> Bool {
        [0].contains(opcode)
    }

    public enum ErrorCode: UInt32, Sendable {
        /// invalid input provided
        case invalidInput = 0
    }

    public enum Anchor: UInt32, Sendable {
        case none = 0
        case top = 1
        case bottom = 2
        case left = 3
        case right = 4
        case topLeft = 5
        case bottomLeft = 6
        case topRight = 7
        case bottomRight = 8
    }

    public enum Gravity: UInt32, Sendable {
        case none = 0
        case top = 1
        case bottom = 2
        case left = 3
        case right = 4
        case topLeft = 5
        case bottomLeft = 6
        case topRight = 7
        case bottomRight = 8
    }

    /// constraint adjustments
    public struct ConstraintAdjustment: OptionSet, Sendable {
        public let rawValue: UInt32
        public init(rawValue: UInt32) { self.rawValue = rawValue }
        /// move along the x axis until unconstrained
        public static let slideX = ConstraintAdjustment(rawValue: 1)
        /// move along the y axis until unconstrained
        public static let slideY = ConstraintAdjustment(rawValue: 2)
        /// invert the anchor and gravity on the x axis
        public static let flipX = ConstraintAdjustment(rawValue: 4)
        /// invert the anchor and gravity on the y axis
        public static let flipY = ConstraintAdjustment(rawValue: 8)
        /// horizontally resize the surface
        public static let resizeX = ConstraintAdjustment(rawValue: 16)
        /// vertically resize the surface
        public static let resizeY = ConstraintAdjustment(rawValue: 32)
    }
}

/// xdg_surface: desktop user interface surface base interface
public enum XdgSurface: Interface {
    public static let name = "xdg_surface"
    public static let version: UInt32 = 7

    public enum Request {
        /// destroy the xdg_surface
        case destroy
        /// assign the xdg_toplevel surface role
        case getToplevel(id: NewID<XdgToplevel>)
        /// assign the xdg_popup surface role
        case getPopup(id: NewID<XdgPopup>, parent: Resource<XdgSurface>?, positioner: Resource<XdgPositioner>)
        /// set the new window geometry
        case setWindowGeometry(x: Int32, y: Int32, width: Int32, height: Int32)
        /// ack a configure event
        case ackConfigure(serial: UInt32)
    }

    public static func decode(opcode: UInt16, from message: inout MessageReader, version: UInt32) throws(ProtocolError) -> Request {
        switch opcode {
        case 0:
            return .destroy
        case 1:
            let id = try message.newID(XdgToplevel.self, version: version)
            return .getToplevel(id: id)
        case 2:
            let id = try message.newID(XdgPopup.self, version: version)
            let parent = try message.optionalObject(XdgSurface.self)
            let positioner = try message.object(XdgPositioner.self)
            return .getPopup(id: id, parent: parent, positioner: positioner)
        case 3:
            let x = try message.int()
            let y = try message.int()
            let width = try message.int()
            let height = try message.int()
            return .setWindowGeometry(x: x, y: y, width: width, height: height)
        case 4:
            let serial = try message.uint()
            return .ackConfigure(serial: serial)
        default:
            throw message.invalidOpcode(opcode)
        }
    }

    public static func isDestructor(opcode: UInt16) -> Bool {
        [0].contains(opcode)
    }

    public enum ErrorCode: UInt32, Sendable {
        /// Surface was not fully constructed
        case notConstructed = 1
        /// Surface was already constructed
        case alreadyConstructed = 2
        /// Attaching a buffer to an unconfigured surface
        case unconfiguredBuffer = 3
        /// Invalid serial number when acking a configure event
        case invalidSerial = 4
        /// Width or height was zero or negative
        case invalidSize = 5
        /// Surface was destroyed before its role object
        case defunctRoleObject = 6
    }
}

extension Resource where I == XdgSurface {
    /// suggest a surface change
    public func sendConfigure(serial: UInt32) {
        guard var event = beginEvent(opcode: 0, since: 1) else { return }
        event.uint(serial)
        send(event)
    }
}

/// xdg_toplevel: toplevel surface
public enum XdgToplevel: Interface {
    public static let name = "xdg_toplevel"
    public static let version: UInt32 = 7

    public enum Request {
        /// destroy the xdg_toplevel
        case destroy
        /// set the parent of this surface
        case setParent(parent: Resource<XdgToplevel>?)
        /// set surface title
        case setTitle(title: String)
        /// set application ID
        case setAppId(appId: String)
        /// show the window menu
        case showWindowMenu(seat: Resource<WlSeat>, serial: UInt32, x: Int32, y: Int32)
        /// start an interactive move
        case move(seat: Resource<WlSeat>, serial: UInt32)
        /// start an interactive resize
        case resize(seat: Resource<WlSeat>, serial: UInt32, edges: UInt32)
        /// set the maximum size
        case setMaxSize(width: Int32, height: Int32)
        /// set the minimum size
        case setMinSize(width: Int32, height: Int32)
        /// maximize the window
        case setMaximized
        /// unmaximize the window
        case unsetMaximized
        /// set the window as fullscreen on an output
        case setFullscreen(output: Resource<WlOutput>?)
        /// unset the window as fullscreen
        case unsetFullscreen
        /// set the window as minimized
        case setMinimized
    }

    public static func decode(opcode: UInt16, from message: inout MessageReader, version: UInt32) throws(ProtocolError) -> Request {
        switch opcode {
        case 0:
            return .destroy
        case 1:
            let parent = try message.optionalObject(XdgToplevel.self)
            return .setParent(parent: parent)
        case 2:
            let title = try message.string()
            return .setTitle(title: title)
        case 3:
            let appId = try message.string()
            return .setAppId(appId: appId)
        case 4:
            let seat = try message.object(WlSeat.self)
            let serial = try message.uint()
            let x = try message.int()
            let y = try message.int()
            return .showWindowMenu(seat: seat, serial: serial, x: x, y: y)
        case 5:
            let seat = try message.object(WlSeat.self)
            let serial = try message.uint()
            return .move(seat: seat, serial: serial)
        case 6:
            let seat = try message.object(WlSeat.self)
            let serial = try message.uint()
            let edges = try message.uint()
            return .resize(seat: seat, serial: serial, edges: edges)
        case 7:
            let width = try message.int()
            let height = try message.int()
            return .setMaxSize(width: width, height: height)
        case 8:
            let width = try message.int()
            let height = try message.int()
            return .setMinSize(width: width, height: height)
        case 9:
            return .setMaximized
        case 10:
            return .unsetMaximized
        case 11:
            let output = try message.optionalObject(WlOutput.self)
            return .setFullscreen(output: output)
        case 12:
            return .unsetFullscreen
        case 13:
            return .setMinimized
        default:
            throw message.invalidOpcode(opcode)
        }
    }

    public static func isDestructor(opcode: UInt16) -> Bool {
        [0].contains(opcode)
    }

    public enum ErrorCode: UInt32, Sendable {
        /// provided value is         not a valid variant of the resize_edge enum
        case invalidResizeEdge = 0
        /// invalid parent toplevel
        case invalidParent = 1
        /// client provided an invalid min or max size
        case invalidSize = 2
    }

    /// edge values for resizing
    public enum ResizeEdge: UInt32, Sendable {
        case none = 0
        case top = 1
        case bottom = 2
        case left = 4
        case topLeft = 5
        case bottomLeft = 6
        case right = 8
        case topRight = 9
        case bottomRight = 10
    }

    /// types of state on the surface
    public enum State: UInt32, Sendable {
        /// the surface is maximized
        case maximized = 1
        /// the surface is fullscreen
        case fullscreen = 2
        /// the surface is being resized
        case resizing = 3
        /// the surface is now activated
        case activated = 4
        /// the surface’s left edge is tiled
        case tiledLeft = 5
        /// the surface’s right edge is tiled
        case tiledRight = 6
        /// the surface’s top edge is tiled
        case tiledTop = 7
        /// the surface’s bottom edge is tiled
        case tiledBottom = 8
        /// surface repaint is suspended
        case suspended = 9
        /// the surface’s left edge is constrained
        case constrainedLeft = 10
        /// the surface’s right edge is constrained
        case constrainedRight = 11
        /// the surface’s top edge is constrained
        case constrainedTop = 12
        /// the surface’s bottom edge is constrained
        case constrainedBottom = 13
    }

    public enum WmCapabilities: UInt32, Sendable {
        /// show_window_menu is available
        case windowMenu = 1
        /// set_maximized and unset_maximized are available
        case maximize = 2
        /// set_fullscreen and unset_fullscreen are available
        case fullscreen = 3
        /// set_minimized is available
        case minimize = 4
    }
}

extension Resource where I == XdgToplevel {
    /// suggest a surface change
    public func sendConfigure(width: Int32, height: Int32, states: [UInt8]) {
        guard var event = beginEvent(opcode: 0, since: 1) else { return }
        event.int(width)
        event.int(height)
        event.array(states)
        send(event)
    }

    /// surface wants to be closed
    public func sendClose() {
        guard let event = beginEvent(opcode: 1, since: 1) else { return }
        send(event)
    }

    /// recommended window geometry bounds
    public func sendConfigureBounds(width: Int32, height: Int32) {
        guard var event = beginEvent(opcode: 2, since: 4) else { return }
        event.int(width)
        event.int(height)
        send(event)
    }

    /// compositor capabilities
    public func sendWmCapabilities(capabilities: [UInt8]) {
        guard var event = beginEvent(opcode: 3, since: 5) else { return }
        event.array(capabilities)
        send(event)
    }
}

/// xdg_popup: short-lived, popup surfaces for menus
public enum XdgPopup: Interface {
    public static let name = "xdg_popup"
    public static let version: UInt32 = 7

    public enum Request {
        /// remove xdg_popup interface
        case destroy
        /// make the popup take an explicit grab
        case grab(seat: Resource<WlSeat>, serial: UInt32)
        /// recalculate the popup's location
        case reposition(positioner: Resource<XdgPositioner>, token: UInt32)
    }

    public static func decode(opcode: UInt16, from message: inout MessageReader, version: UInt32) throws(ProtocolError) -> Request {
        switch opcode {
        case 0:
            return .destroy
        case 1:
            let seat = try message.object(WlSeat.self)
            let serial = try message.uint()
            return .grab(seat: seat, serial: serial)
        case 2:
            guard version >= 3 else { throw message.invalidOpcode(opcode) }
            let positioner = try message.object(XdgPositioner.self)
            let token = try message.uint()
            return .reposition(positioner: positioner, token: token)
        default:
            throw message.invalidOpcode(opcode)
        }
    }

    public static func isDestructor(opcode: UInt16) -> Bool {
        [0].contains(opcode)
    }

    public enum ErrorCode: UInt32, Sendable {
        /// tried to grab after being mapped
        case invalidGrab = 0
    }
}

extension Resource where I == XdgPopup {
    /// configure the popup surface
    public func sendConfigure(x: Int32, y: Int32, width: Int32, height: Int32) {
        guard var event = beginEvent(opcode: 0, since: 1) else { return }
        event.int(x)
        event.int(y)
        event.int(width)
        event.int(height)
        send(event)
    }

    /// popup interaction is done
    public func sendPopupDone() {
        guard let event = beginEvent(opcode: 1, since: 1) else { return }
        send(event)
    }

    /// signal the completion of a repositioned request
    public func sendRepositioned(token: UInt32) {
        guard var event = beginEvent(opcode: 2, since: 3) else { return }
        event.uint(token)
        send(event)
    }
}
