// swift-tools-version: 6.4
//
// mydistro's user interface, written in Swift.
//
// The C libraries below are the only non-Swift layer: they are how a Linux
// display server talks to the kernel (DRM/KMS, input devices), plus font
// rasterisation and shaping. The Wayland server is Swift (the Wayland
// target); libwayland-client is here only for the test client, as apps use
// it. Everything above them — compositor, window management, shell,
// toolkit — is meant to be Swift.

import PackageDescription

// A C library, wrapped as a Swift module (Sources/<name>/module.modulemap +
// shim.h; the module map names the library to link). `package` is the Arch
// Linux package that provides it (a dependency of the mydistro-ui package).
//
// On Linux, pkg-config gives the compiler flags. On a Mac, the build uses the
// mydistro Swift SDK (`make sdk`), which has the include directories. There,
// pkg-config would find Homebrew's macOS libraries, so it is not used.
func system(_ name: String, pkgConfig: String, package: String) -> Target {
    #if os(Linux)
    .systemLibrary(name: name, pkgConfig: pkgConfig)
    #else
    .systemLibrary(name: name)
    #endif
}

let package = Package(
    name: "mydistro-ui",
    products: [
        .library(name: "DRMKit", targets: ["DRMKit"]),
        .library(name: "Wayland", targets: ["Wayland"]),
        .library(name: "Compositor", targets: ["Compositor"]),
        .executable(name: "mydistro-compositor", targets: ["CompositorMain"]),
        .executable(name: "mydistro-hello-client", targets: ["HelloClient"]),
        .executable(name: "mydistro-display-probe", targets: ["DisplayProbe"]),
        .executable(name: "mydistro-ui-check", targets: ["UICheck"]),
    ],
    targets: [
        // Display: kernel mode setting and buffers.
        system("CDRM", pkgConfig: "libdrm", package: "libdrm"),
        system("CGBM", pkgConfig: "gbm", package: "mesa"),
        // GPU rendering (Mesa; software rendering in the QEMU VM).
        system("CEGL", pkgConfig: "egl", package: "mesa"),
        system("CGLES", pkgConfig: "glesv2", package: "mesa"),
        // Input: devices, hotplug, keymaps, and seat (device access) management.
        system("CInput", pkgConfig: "libinput", package: "libinput"),
        system("CUdev", pkgConfig: "libudev", package: "systemd-libs"),
        system("CXKBCommon", pkgConfig: "xkbcommon", package: "libxkbcommon"),
        system("CSeat", pkgConfig: "libseat", package: "seatd"),
        // The Wayland client library, for the test client.
        system("CWaylandClient", pkgConfig: "wayland-client", package: "wayland"),
        // Text: glyph rasterisation and shaping.
        system("CFreeType", pkgConfig: "freetype2", package: "freetype2"),
        system("CHarfBuzz", pkgConfig: "harfbuzz", package: "harfbuzz"),

        // xdg-shell for the test client, generated by Scripts/generate-protocols.sh.
        .target(name: "CXDGShellClient", dependencies: ["CWaylandClient"]),

        // The Wayland server in Swift: event loop, sockets, wire format,
        // objects, wl_shm, and the protocol code that Tools/WaylandScanner
        // makes from Protocols/*.xml. No C code: CLinux only imports the
        // epoll and signalfd headers of glibc.
        .systemLibrary(name: "CLinux"),
        .target(name: "Wayland", dependencies: ["CLinux"]),

        // Swift layer over DRM/KMS: find outputs, allocate buffers, show them.
        // (Not named "DRM": on a case-insensitive Mac file system, its
        // libDRM.a would hide libdrm.so from the linker.)
        .target(name: "DRMKit", dependencies: ["CDRM"]),

        // The compositor: screen, input, seat, window list, display list and
        // software renderer, and the Wayland globals that apps use.
        .target(name: "Compositor", dependencies: [
            "DRMKit", "CDRM", "CInput", "CUdev", "CXKBCommon", "CSeat", "Wayland",
        ]),
        .executableTarget(name: "CompositorMain", dependencies: ["Compositor"]),

        // A minimal Wayland app (one coloured window), for testing the compositor.
        .executableTarget(name: "HelloClient", dependencies: ["CWaylandClient", "CXDGShellClient"]),

        // Takes over the screen and draws a test pattern (used by tests/display.exp).
        .executableTarget(name: "DisplayProbe", dependencies: ["DRMKit"]),

        // Links against every C library above and exercises each one briefly:
        // proves the toolchain, the module maps and the target's runtime libraries.
        .executableTarget(name: "UICheck", dependencies: [
            "CDRM", "CGBM", "CEGL", "CGLES", "CInput", "CUdev", "CXKBCommon", "CSeat",
            "CWaylandClient", "CFreeType", "CHarfBuzz",
        ]),
    ]
)
