// swift-tools-version: 6.4
//
// mydistro's user interface, written in Swift.
//
// The C libraries below are the only non-Swift layer: they are how any Linux
// display server talks to the kernel (DRM/KMS, input devices) and to apps
// (Wayland), plus font rasterisation and shaping. Everything above them —
// compositor, window management, shell, toolkit — is meant to be Swift.

import PackageDescription

// A C library, wrapped as a Swift module (Sources/<name>/module.modulemap +
// shim.h; the module map names the library to link). `package` is the Arch
// Linux package that provides it (a dependency of the mydistro-ui package).
//
// On Linux, pkg-config gives the compiler flags. On a Mac, the build uses the
// mydistro Swift SDK (`make sdk`), which has the include directories. There,
// pkg-config would find Homebrew's macOS libraries, so it is not used.
func system(_ name: String, pkgConfig: String, package: String) -> Target {
    #if os(Linux)
    .systemLibrary(name: name, pkgConfig: pkgConfig)
    #else
    .systemLibrary(name: name)
    #endif
}

let package = Package(
    name: "mydistro-ui",
    products: [
        .library(name: "DRMKit", targets: ["DRMKit"]),
        .library(name: "Compositor", targets: ["Compositor"]),
        .executable(name: "mydistro-compositor", targets: ["CompositorMain"]),
        .executable(name: "mydistro-hello-client", targets: ["HelloClient"]),
        .executable(name: "mydistro-display-probe", targets: ["DisplayProbe"]),
        .executable(name: "mydistro-ui-check", targets: ["UICheck"]),
    ],
    targets: [
        // Display: kernel mode setting and buffers.
        system("CDRM", pkgConfig: "libdrm", package: "libdrm"),
        system("CGBM", pkgConfig: "gbm", package: "mesa"),
        // GPU rendering (Mesa; software rendering in the QEMU VM).
        system("CEGL", pkgConfig: "egl", package: "mesa"),
        system("CGLES", pkgConfig: "glesv2", package: "mesa"),
        // Input: devices, hotplug, keymaps, and seat (device access) management.
        system("CInput", pkgConfig: "libinput", package: "libinput"),
        system("CUdev", pkgConfig: "libudev", package: "systemd-libs"),
        system("CXKBCommon", pkgConfig: "xkbcommon", package: "libxkbcommon"),
        system("CSeat", pkgConfig: "libseat", package: "seatd"),
        // The Wayland protocol, for the compositor and for apps.
        system("CWaylandServer", pkgConfig: "wayland-server", package: "wayland"),
        system("CWaylandClient", pkgConfig: "wayland-client", package: "wayland"),
        // Text: glyph rasterisation and shaping.
        system("CFreeType", pkgConfig: "freetype2", package: "freetype2"),
        system("CHarfBuzz", pkgConfig: "harfbuzz", package: "harfbuzz"),

        // Wayland protocol extensions, generated by Scripts/generate-protocols.sh.
        .target(name: "CXDGShellServer", dependencies: ["CWaylandServer"]),
        .target(name: "CXDGShellClient", dependencies: ["CWaylandClient"]),

        // Swift layer over DRM/KMS: find outputs, allocate buffers, show them.
        // (Not named "DRM": on a case-insensitive Mac file system, its
        // libDRM.a would hide libdrm.so from the linker.)
        .target(name: "DRMKit", dependencies: ["CDRM"]),

        // The compositor: screen, input, seat, Wayland server, window list,
        // display list and software renderer.
        .target(name: "Compositor", dependencies: [
            "DRMKit", "CDRM", "CInput", "CUdev", "CXKBCommon", "CSeat", "CWaylandServer", "CXDGShellServer",
        ]),
        .executableTarget(name: "CompositorMain", dependencies: ["Compositor"]),

        // A minimal Wayland app (one coloured window), for testing the compositor.
        .executableTarget(name: "HelloClient", dependencies: ["CWaylandClient", "CXDGShellClient"]),

        // Takes over the screen and draws a test pattern (used by tests/display.exp).
        .executableTarget(name: "DisplayProbe", dependencies: ["DRMKit"]),

        // Links against every C library above and exercises each one briefly:
        // proves the toolchain, the module maps and the target's runtime libraries.
        .executableTarget(name: "UICheck", dependencies: [
            "CDRM", "CGBM", "CEGL", "CGLES", "CInput", "CUdev", "CXKBCommon", "CSeat",
            "CWaylandServer", "CWaylandClient", "CFreeType", "CHarfBuzz",
        ]),
    ]
)
