// swift-tools-version: 6.4
//
// mydistro's display server, written in Swift.
//
// This package is the system side of the user interface: the compositor, the
// Wayland server, the display and input drivers, and the test programs. It
// builds for mydistro only (aarch64 Linux).
//
// The user interface that mydistro draws — the toolkit and the shell — is the
// package in Toolkit/. That package also builds on macOS, so its tests run in
// seconds and Xcode gives code completion for it. Write UI code there.
//
// The C libraries below are the only non-Swift layer: they are how a Linux
// display server talks to the kernel (DRM/KMS, input devices). The Wayland
// server is Swift (the Wayland target). libwayland-client is here only for
// the test client, as apps use it.

import PackageDescription

// A C library, wrapped as a Swift module (Sources/<name>/module.modulemap +
// shim.h; the module map names the library to link). `package` is the Arch
// Linux package that provides it (a dependency of the mydistro-ui package).
//
// On Linux, pkg-config gives the compiler flags. On a Mac, the build uses the
// mydistro Swift SDK (`make sdk`), which has the include directories. There,
// pkg-config would find Homebrew's macOS libraries, so it is not used.
func system(_ name: String, pkgConfig: String, package: String) -> Target {
    #if os(Linux)
    .systemLibrary(name: name, pkgConfig: pkgConfig)
    #else
    .systemLibrary(name: name)
    #endif
}

let package = Package(
    name: "mydistro-ui",
    products: [
        .library(name: "DRMKit", targets: ["DRMKit"]),
        .library(name: "Wayland", targets: ["Wayland"]),
        .library(name: "Compositor", targets: ["Compositor"]),
        .executable(name: "mydistro-compositor", targets: ["CompositorMain"]),
        .executable(name: "mydistro-hello-client", targets: ["HelloClient"]),
        .executable(name: "mydistro-terminal", targets: ["TerminalApp"]),
        .executable(name: "mydistro-display-probe", targets: ["DisplayProbe"]),
        .executable(name: "mydistro-ui-check", targets: ["UICheck"]),
        .executable(name: "mydistro-screen", targets: ["ScreenTool"]),
    ],
    dependencies: [
        // The toolkit and the shell. The name of a dependency on a directory
        // is the name of the directory ("Toolkit"), not the name in its
        // manifest ("mydistro-toolkit").
        .package(path: "Toolkit"),
    ],
    targets: [
        // Display: kernel mode setting and buffers.
        system("CDRM", pkgConfig: "libdrm", package: "libdrm"),
        system("CGBM", pkgConfig: "gbm", package: "mesa"),
        // GPU rendering (Mesa; software rendering in the QEMU VM).
        system("CEGL", pkgConfig: "egl", package: "mesa"),
        system("CGLES", pkgConfig: "glesv2", package: "mesa"),
        // Input: devices, hotplug, keymaps, and seat (device access) management.
        system("CInput", pkgConfig: "libinput", package: "libinput"),
        system("CUdev", pkgConfig: "libudev", package: "systemd-libs"),
        system("CXKBCommon", pkgConfig: "xkbcommon", package: "libxkbcommon"),
        system("CSeat", pkgConfig: "libseat", package: "seatd"),
        // The Wayland client library, for the test client.
        system("CWaylandClient", pkgConfig: "wayland-client", package: "wayland"),

        // xdg-shell for the test client, generated by Scripts/generate-protocols.sh.
        .target(name: "CXDGShellClient", dependencies: ["CWaylandClient"]),

        // The Wayland server in Swift: event loop, sockets, wire format,
        // objects, wl_shm, and the protocol code that Tools/WaylandScanner
        // makes from Protocols/*.xml. No C code: CLinux only imports the
        // epoll and signalfd headers of glibc.
        .systemLibrary(name: "CLinux"),
        .target(name: "Wayland", dependencies: ["CLinux"]),

        // Swift layer over DRM/KMS: find outputs, allocate buffers, show them.
        // (Not named "DRM": on a case-insensitive Mac file system, its
        // libDRM.a would hide libdrm.so from the linker.)
        .target(name: "DRMKit", dependencies: ["CDRM"]),

        // The compositor: screen, input, seat, window list, and the Wayland
        // globals that apps use. It draws the shell with the toolkit.
        .target(name: "Compositor", dependencies: [
            "DRMKit", "CDRM", "CInput", "CUdev", "CXKBCommon", "CSeat", "Wayland",
            .product(name: "Render", package: "Toolkit"),
            .product(name: "Toolkit", package: "Toolkit"),
            .product(name: "Shell", package: "Toolkit"),
        ]),
        .executableTarget(name: "CompositorMain", dependencies: ["Compositor"]),

        // A minimal Wayland app (one coloured window), for testing the compositor.
        .executableTarget(name: "HelloClient", dependencies: ["CWaylandClient", "CXDGShellClient"]),

        // The terminal: an app of the system. It opens a window, runs a
        // shell on a pseudo terminal, and draws what the shell prints. The
        // grid of characters and the escape sequences are the Terminal
        // module of the toolkit package, which the Mac tests. The bundle in
        // Apps/Terminal.app puts the program in /Applications.
        .target(name: "CPTY"),
        .executableTarget(name: "TerminalApp", dependencies: [
            "CWaylandClient", "CXDGShellClient", "CXKBCommon", "CPTY",
            .product(name: "Render", package: "Toolkit"),
            .product(name: "Toolkit", package: "Toolkit"),
            .product(name: "Terminal", package: "Toolkit"),
        ]),

        // What a test on the Mac uses to see and to touch the screen: it
        // asks the compositor for the pixels, and makes a pointer and a
        // keyboard with uinput. Virtualization, unlike QEMU, can do neither
        // of these from the host.
        .target(name: "CUinput"),
        .executableTarget(name: "ScreenTool", dependencies: ["CUinput"]),

        // Takes over the screen and draws a test pattern (used by tests/display.exp).
        .executableTarget(name: "DisplayProbe", dependencies: ["DRMKit"]),

        // Links against every C library above and exercises each one briefly:
        // proves the toolchain, the module maps and the target's runtime libraries.
        .executableTarget(name: "UICheck", dependencies: [
            "CDRM", "CGBM", "CEGL", "CGLES", "CInput", "CUdev", "CXKBCommon", "CSeat",
            "CWaylandClient",
            .product(name: "CFreeType", package: "Toolkit"),
            .product(name: "CHarfBuzz", package: "Toolkit"),
        ]),
    ]
)
